wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1643663956
    t:
      1:
      - 1
      4: 3.9.5
      5: 0.12.9
      8:
      - 5
batch_size:
  desc: null
  value: 195
epochs:
  desc: null
  value: 1
layer1_size:
  desc: null
  value: 256
layer2_size:
  desc: null
  value: 512
learning_rate:
  desc: null
  value: 0.02523039639596334
optimizer:
  desc: null
  value: adam
