wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1643647095
    t:
      1:
      - 1
      3:
      - 17
      4: 3.9.5
      5: 0.12.9
      8:
      - 5
learning_rate:
  desc: null
  value: 0.000978281746955754
optimizer:
  desc: null
  value: adam
